name: Build Launcher (Linux)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install .NET SDK manually
        run: |
          set -x
          curl -sSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --channel 10.0
          echo "DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV
          echo "$HOME/.dotnet" >> $GITHUB_PATH
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore & build
        run: |
          set -x
          cd Launcher
          dotnet restore
          dotnet build -c Release

      - name: Upload artifact/s
        uses: actions/upload-artifact@v4
        with:
          name: Launcher
          path: |
            Launcher/bin/Release/net10.0-windows/win-x64
